name: graph-signal-processing
channels:
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.9
  - numpy>=1.19.2
  - scipy>=1.6.0
  - scikit-learn>=0.24.0
  - networkx>=2.5.1
  - matplotlib>=3.3.4
  - seaborn>=0.11.1
  - pandas>=1.3.0
  - jupyter
  - notebook
  - ipykernel
  - tqdm>=4.65.0
  - pytorch>=1.9.0
  - pyg::torch-geometric>=2.4.0
  - pyg::torch-scatter>=2.1.2
  - pyg::torch-sparse>=0.6.18
  - pip
  - pip:
    - pygsp>=0.5.1
